# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/jaisw/OneDrive/Desktop/cache

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/jaisw/OneDrive/Desktop/cache/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/jaisw/OneDrive/Desktop/cache/build/CMakeFiles /mnt/c/Users/jaisw/OneDrive/Desktop/cache/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/jaisw/OneDrive/Desktop/cache/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lru_cache

# Build rule for target.
lru_cache: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lru_cache
.PHONY : lru_cache

# fast build rule for target.
lru_cache/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lru_cache.dir/build.make CMakeFiles/lru_cache.dir/build
.PHONY : lru_cache/fast

#=============================================================================
# Target rules for targets named cache_server

# Build rule for target.
cache_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cache_server
.PHONY : cache_server

# fast build rule for target.
cache_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cache_server.dir/build.make CMakeFiles/cache_server.dir/build
.PHONY : cache_server/fast

#=============================================================================
# Target rules for targets named lru_cache_tests

# Build rule for target.
lru_cache_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lru_cache_tests
.PHONY : lru_cache_tests

# fast build rule for target.
lru_cache_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lru_cache_tests.dir/build.make CMakeFiles/lru_cache_tests.dir/build
.PHONY : lru_cache_tests/fast

#=============================================================================
# Target rules for targets named lru_cache_benchmark

# Build rule for target.
lru_cache_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lru_cache_benchmark
.PHONY : lru_cache_benchmark

# fast build rule for target.
lru_cache_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lru_cache_benchmark.dir/build.make CMakeFiles/lru_cache_benchmark.dir/build
.PHONY : lru_cache_benchmark/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) $(MAKESILENT) -f _deps/benchmark-build/src/CMakeFiles/benchmark.dir/build.make _deps/benchmark-build/src/CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

#=============================================================================
# Target rules for targets named benchmark_main

# Build rule for target.
benchmark_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_main
.PHONY : benchmark_main

# fast build rule for target.
benchmark_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/benchmark-build/src/CMakeFiles/benchmark_main.dir/build.make _deps/benchmark-build/src/CMakeFiles/benchmark_main.dir/build
.PHONY : benchmark_main/fast

benchmarks/benchmark_lru_cache.o: benchmarks/benchmark_lru_cache.cpp.o
.PHONY : benchmarks/benchmark_lru_cache.o

# target to build an object file
benchmarks/benchmark_lru_cache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lru_cache_benchmark.dir/build.make CMakeFiles/lru_cache_benchmark.dir/benchmarks/benchmark_lru_cache.cpp.o
.PHONY : benchmarks/benchmark_lru_cache.cpp.o

benchmarks/benchmark_lru_cache.i: benchmarks/benchmark_lru_cache.cpp.i
.PHONY : benchmarks/benchmark_lru_cache.i

# target to preprocess a source file
benchmarks/benchmark_lru_cache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lru_cache_benchmark.dir/build.make CMakeFiles/lru_cache_benchmark.dir/benchmarks/benchmark_lru_cache.cpp.i
.PHONY : benchmarks/benchmark_lru_cache.cpp.i

benchmarks/benchmark_lru_cache.s: benchmarks/benchmark_lru_cache.cpp.s
.PHONY : benchmarks/benchmark_lru_cache.s

# target to generate assembly for a file
benchmarks/benchmark_lru_cache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lru_cache_benchmark.dir/build.make CMakeFiles/lru_cache_benchmark.dir/benchmarks/benchmark_lru_cache.cpp.s
.PHONY : benchmarks/benchmark_lru_cache.cpp.s

src/LRUCache.o: src/LRUCache.cpp.o
.PHONY : src/LRUCache.o

# target to build an object file
src/LRUCache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lru_cache.dir/build.make CMakeFiles/lru_cache.dir/src/LRUCache.cpp.o
.PHONY : src/LRUCache.cpp.o

src/LRUCache.i: src/LRUCache.cpp.i
.PHONY : src/LRUCache.i

# target to preprocess a source file
src/LRUCache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lru_cache.dir/build.make CMakeFiles/lru_cache.dir/src/LRUCache.cpp.i
.PHONY : src/LRUCache.cpp.i

src/LRUCache.s: src/LRUCache.cpp.s
.PHONY : src/LRUCache.s

# target to generate assembly for a file
src/LRUCache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lru_cache.dir/build.make CMakeFiles/lru_cache.dir/src/LRUCache.cpp.s
.PHONY : src/LRUCache.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cache_server.dir/build.make CMakeFiles/cache_server.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cache_server.dir/build.make CMakeFiles/cache_server.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cache_server.dir/build.make CMakeFiles/cache_server.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/server.o: src/server.cpp.o
.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cache_server.dir/build.make CMakeFiles/cache_server.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cache_server.dir/build.make CMakeFiles/cache_server.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cache_server.dir/build.make CMakeFiles/cache_server.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

tests/test_lru_cache.o: tests/test_lru_cache.cpp.o
.PHONY : tests/test_lru_cache.o

# target to build an object file
tests/test_lru_cache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lru_cache_tests.dir/build.make CMakeFiles/lru_cache_tests.dir/tests/test_lru_cache.cpp.o
.PHONY : tests/test_lru_cache.cpp.o

tests/test_lru_cache.i: tests/test_lru_cache.cpp.i
.PHONY : tests/test_lru_cache.i

# target to preprocess a source file
tests/test_lru_cache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lru_cache_tests.dir/build.make CMakeFiles/lru_cache_tests.dir/tests/test_lru_cache.cpp.i
.PHONY : tests/test_lru_cache.cpp.i

tests/test_lru_cache.s: tests/test_lru_cache.cpp.s
.PHONY : tests/test_lru_cache.s

# target to generate assembly for a file
tests/test_lru_cache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lru_cache_tests.dir/build.make CMakeFiles/lru_cache_tests.dir/tests/test_lru_cache.cpp.s
.PHONY : tests/test_lru_cache.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... benchmark"
	@echo "... benchmark_main"
	@echo "... cache_server"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... lru_cache"
	@echo "... lru_cache_benchmark"
	@echo "... lru_cache_tests"
	@echo "... benchmarks/benchmark_lru_cache.o"
	@echo "... benchmarks/benchmark_lru_cache.i"
	@echo "... benchmarks/benchmark_lru_cache.s"
	@echo "... src/LRUCache.o"
	@echo "... src/LRUCache.i"
	@echo "... src/LRUCache.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... tests/test_lru_cache.o"
	@echo "... tests/test_lru_cache.i"
	@echo "... tests/test_lru_cache.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

